#!/bin/bash
source ~/.functions
export CURR_DIR=$(pwd)
export EX_DIR='/home/anthony-walker/nrg-cantera-project/cantera-adaptive-testing/examples'
rebuildCantera
cd $EX_DIR
scons;
./dev-test.out;
gprof -Q -D -b dev-test.out gmon.out>$CURR_DIR/profiles/$1

# -Q no call graph
# -D ignore non-functions
